### ISSUE TITLE
Quarry causes the server to crash

### ISSUE THREAD

**Issue by ghost** [WTBW-Mods/WTBW_Machines#16]
I'm running a small FTB onmia server and the quarry crashes the server every time it's used. I don't know exactly why but 2 separate times (after having to restore the server from a backup) after placing the quarry and letting it mine for a minute or 2, the next time that chunk is loaded (if I leave the mining dim then come back) it causes a crash. The first time I had an upgrade on it and it had only mined dirt, the 2nd time it has no upgrades and was mining straight down.

**Comment by Sunekaer** [comment]
Logs?

**Comment by ghost** [comment]
[crash-2020-05-04_17.19.45-server.txt](https://github.com/WTBW-Mods/WTBW_Machines/files/4578517/crash-2020-05-04_17.19.45-server.txt)
[crash-2020-05-04_17.25.06-server.txt](https://github.com/WTBW-Mods/WTBW_Machines/files/4578518/crash-2020-05-04_17.25.06-server.txt)
[crash-2020-05-04_06.56.36-server.txt](https://github.com/WTBW-Mods/WTBW_Machines/files/4578519/crash-2020-05-04_06.56.36-server.txt)
[crash-2020-05-04_06.59.52-server.txt](https://github.com/WTBW-Mods/WTBW_Machines/files/4578520/crash-2020-05-04_06.59.52-server.txt)


These are the logs from earlier, 2 for each occurrence from the server trying to turn back on before I restored a backup. 

I did try to replicate the issue a 3rd time and it seems to work fine now even with the same pipes going in and out of it, it hasn't crashed after an hour of it running. If it happens again I'll post the new logs.

**Comment by Naxanria** [comment]
It is the server watchdog stopping the server after it being non-responsive for a while. I dont see anything wtbw related in there.
