### ISSUE TITLE
don't work simple storage

### ISSUE THREAD

**Issue by AndyDL24** [WTBW-Mods/WTBW_Machines#17]
Hi, this mod doesn't work with a simple storage network ... don't take it with an import cable. And add the option to select on the output element or on the input element in the machine GUI it is easier to choose the destination or connect more nearby machines. obviously they are only ideas of your choice.
I'm sorry for my english, but I'm an italian boy

**Comment by Naxanria** [comment]
I cant replicate. Only thing I have noticed is the output number is changing, it doesnt pull it out. 
But it does work. If you have more issues with it, I would suggest making an issue on their tracker :)
