### ISSUE TITLE
[1.15.2-1.0.7] Block break dupe glitch

### ISSUE THREAD

**Issue by kreezxil** [WTBW-Mods/WTBW_Machines#5]
When harvesting a quarry. The quarry will duplicate.

I can make a video of this if you want to see it in action. I discovered it yesterday in my Foreshadowing modpack of which I'm the author. Another player reported it on my tracker before I made this one.

We're on Forge 1.15.2-31.1.1

our latest.log from the server in case it might help you: https://gist.github.com/87f3ca42c4a6a288274ae846981f4fa0

**Comment by kreezxil** [comment]
@Sunekaer I can make a video showcasing this dupe if that will be helpful to you?

**Comment by Sunekaer** [comment]
Well it doesnt drop for me in single player.
Can you reproduce it without anyother mods?

**Comment by kreezxil** [comment]
it's in multiplayer.

**Comment by Sunekaer** [comment]
And only the quarry does it?

**Comment by Naxanria** [comment]
Fix has been pushed. Also update library to 1.0.9+

**Comment by kreezxil** [comment]
Sweet, thank you so much. :)
