### ISSUE TITLE
negative values in FE gauge of crusher

### ISSUE THREAD

**Issue by random51** [WTBW-Mods/WTBW_Machines#7]
Version: 1.15.2-1.0.10
Forge: 31.1.18

![crusher_fe](https://user-images.githubusercontent.com/12644511/76162516-7e9de400-610c-11ea-8225-f4ad2c971884.jpg)

**Comment by Sunekaer** [comment]
Server issue

**Comment by Sunekaer** [comment]
![image](https://user-images.githubusercontent.com/18720460/76168445-3f08e380-6170-11ea-8d7b-d7a568246a44.png)
SP^ same pack

**Comment by Sunekaer** [comment]
![image](https://user-images.githubusercontent.com/18720460/76168462-56e06780-6170-11ea-8a96-2051fdd8d0ab.png)
